name: Automated Tests with Allure Report

on:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 1. Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # СТРОКУ С PLAYWRIGHT Я УБРАЛ — ОНА ВЫЗЫВАЛА ОШИБКУ 127

      # 2. Запускаем тесты
      - name: Run Tests
        run: python -m pytest tests/ --alluredir=allure-results
        continue-on-error: true

      # 3. Скачиваем историю (если ветки нет — ошибка игнорируется)
      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true  # <--- ВОТ ЭТА МАГИЯ. Она позволяет не падать на первом запуске.
        with:
          ref: gh-pages
          path: gh-pages

      # 4. Строим отчет
      - name: Build Allure report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: allure-results
          allure_report: allure-report

      # 5. Публикуем (если ветки нет — она создастся сама)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
